Fix YDBTest/sudo/plugins subtest failure when built with clang (due to -pedantic in CMakeLists.txt)
Background
----------
* The `sudo/plugins` subtest failed during in-house testing on Ubuntu 24.04 systems while
  installing the `YDBCurl` plugin.

* The version of `clang` was `18.1.3` on those systems and when this was used as the compiler
  (e.g. setting `CC` env var to `clang`) while building the `YDBCurl` project, one got the
  following compilation errors.

  ```sh
  $ cd YDBCurl
  $ mkdir build
  $ cd build
  $ cmake ..
  $ make
  [ 10%] Building C object CMakeFiles/curl.dir/libcurl.c.o
  In file included from YDBCurl/libcurl.c:23:
  /usr/library/V999_R201/dbg/gtmxc_types.h:79:78: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
     79 | void            gtm_start_timer(ydb_tid_t tid, ydb_int_t time_to_expir, void (*handler)(), ydb_int_t hdata_len, void *hdata);
        |                                                                                        ^
        |                                                                                         void
  YDBCurl/libcurl.c:77:23: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
     77 | gtm_status_t curl_init()
        |                       ^
        |                        void
  YDBCurl/libcurl.c:96:26: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
     96 | gtm_status_t curl_cleanup()
        |                          ^
        |                           void
  YDBCurl/libcurl.c:360:9: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
    360 | int main() /* tester routine to make sure everything still works */
        |         ^
        |          void
  4 errors generated.
  ```

Issue
-----
* There are 3 errors identified in `YDBCurl/libcurl.c` and 1 error identified in `YDB/sr_unix/gtmxc_types.h`.
  All of them are `-Wstrict-prototypes`.

* Commit 175b859 had recently set `CMAKE_C_FLAGS` to `-Wall -Wextra -Werror -pedantic`.

* Out of these, it is `-pedantic` that causes `-Wstrict-prototypes` to be enabled in `clang 18.1.3`.

* As described at https://stackoverflow.com/a/73312779, `-pedantic` is more of a nuisance than help in
  various cases. The above failure is one such example. There is nothing wrong in the identified
  lines.

Fix
---
* It is not considered necessary to enable `-pedantic` for `YDBCurl` and so this commit removes that part.

Misc
----
* Additionally, `/build/` was added to `.gitignore` to avoid it from showing up as untracked directory.
  This lets us maintain a `YDBCurl/build/` subdirectory for doing local builds (using cmake,make etc.)
  without worrying about those files getting added by `git` during a `git commit`.

  While at this, I also noticed that `.gitignore` did not have a YottaDB copyright so fixed that too
  (else `commit-verify` pipeline job failed).

* Note that a similar test failure happened on a `RHEL 9` system as well where the clang version was
  `clang 17.0`. So the issue happens from `clang 17` and higher versions.